/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-11-10 10:12:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/css-files/style3.css", Long.valueOf(1415603269003L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    ");
      out.write(".container:before, .container:after {\r\n");
      out.write("    display:table;\r\n");
      out.write("    content:\"\";\r\n");
      out.write("    zoom:1 /* ie fix */;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container:after {\r\n");
      out.write("    clear:both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\t/*top:700px;*/\r\n");
      out.write("    width:80% !important;\r\n");
      out.write("    margin:0 auto;\r\n");
      out.write("    border:1px solid ;\r\n");
      out.write("    box-shadow:0px 2px 7px #292929;\r\n");
      out.write("    -moz-box-shadow: 0px 2px 7px #292929;\r\n");
      out.write("    -webkit-box-shadow: 0px 2px 7px #292929;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    -moz-border-radius:10px;\r\n");
      out.write("    -webkit-border-radius:10px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mainbody {\r\n");
      out.write("\t background-color:#F0FFFF;\r\n");
      out.write("\ttop:200px;\r\n");
      out.write("    height:500px;\r\n");
      out.write("    \twidth:100%;\r\n");
      out.write("    /* width:800px; */\r\n");
      out.write("    border: solid #eee;\r\n");
      out.write("    border-width:1px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".submainbody {\r\n");
      out.write("\t background-color: #FFF0F5;\r\n");
      out.write("\t/* background: linear-gradient(180deg, red, blue); */\r\n");
      out.write("\ttop:250px;\r\n");
      out.write("    height:30px;\r\n");
      out.write("    /* width:800px; */\r\n");
      out.write("    \twidth:100%;\r\n");
      out.write("    border: #eee;\r\n");
      out.write("   /*  border-width:1px 0; */\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/* font-color:#FFF0F5; */\r\n");
      out.write("\t/* text-color:#FFF0F5; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".header, .footer {\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("     border: #eee;\r\n");
      out.write("    background-color: #b0c4de;\r\n");
      out.write("    /*  background-color:#E6E6FA; */\r\n");
      out.write("    font-color:green;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tables\r\n");
      out.write("{position:relative;\r\n");
      out.write("    /* height:400px; */\r\n");
      out.write("    \twidth:100%;\r\n");
      out.write("    /* width:800px; */\r\n");
      out.write("    border: solid #eee;\r\n");
      out.write("    border-width:1px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    \r\n");
      out.write("    -webkit-border-bottom-right-radius:5px;\r\n");
      out.write("    -webkit-border-bottom-left-radius:5px;\r\n");
      out.write("    -moz-border-radius-bottomright:5px;\r\n");
      out.write("    -moz-border-radius-bottomleft:5px;\r\n");
      out.write("    border-bottom-right-radius:5px;\r\n");
      out.write("    border-bottom-left-radius:5px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("H1\r\n");
      out.write(" {  color: #800000;\r\n");
      out.write("    font-family: \"Algerian\";\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("H2\r\n");
      out.write("{  color: #800000;\r\n");
      out.write("    font-family: \"Verdana\";\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("H3\r\n");
      out.write("{  color: black ;\r\n");
      out.write("     font-family: \"Verdana\";\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size:smaller;\r\n");
      out.write("}\r\n");
      out.write("H5\r\n");
      out.write("{  color: black ;\r\n");
      out.write("     font-family: \"Verdana\";\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/* font-size:smaller; */\r\n");
      out.write("}\r\n");
      out.write("H6\r\n");
      out.write(" {  color: #8B4513;\r\n");
      out.write("    font-family: \"Comic Sans MS\", cursive, sans-serif;\r\n");
      out.write("\tfont-weight: 800;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size:smaller;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout {\r\n");
      out.write("\tposition:fixed;\r\n");
      out.write("    /* background-color: cyan; */\r\n");
      out.write("\ttop:0px;\r\n");
      out.write("\tleft:85%;\r\n");
      out.write("    height:70px;\r\n");
      out.write("    width:200px;\r\n");
      out.write("    border: solid #eee;\r\n");
      out.write("    border-width:1px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  .logo\r\n");
      out.write("  { /* position:fixed; */\r\n");
      out.write("    /* background-color: red; */\r\n");
      out.write("\ttop:0px;\r\n");
      out.write("\tleft:0px;\r\n");
      out.write("    height:70px;\r\n");
      out.write("    width:200px;\r\n");
      out.write("    border: solid #eee;\r\n");
      out.write("    border-width:1px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write(" body{\r\n");
      out.write("  background-image:url(green.jpg)\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<title>CPMS</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"300px\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/centurylink-logo.png\" alt=\"Centurylink\" height=\"50px\">\r\n");
      out.write("        </td>\r\n");
      out.write("        <td><h2>CAR POOL MANAGEMENT SYSTEM</h2></td>\r\n");
      out.write("        <td align=\"right\" width=\"200px\">\r\n");
      out.write("           \r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<h2>LOGIN</h2>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mainbody\">\r\n");
      out.write("\r\n");
      out.write("<form id=\"login\" name=\"login\" onsubmit=\"return true;\" action=\"/cpms/login.action\" method=\"post\">\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tCUID:  &nbsp&nbsp&nbsp&nbsp<input type=\"text\" name=\"cuid\"  />\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\tPassword:<input type=\"password\" name=\"password\"   />\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input type=\"submit\" id=\"login_0\" value=\"  Login  \"/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<h5>New to CPMS?</h5>\r\n");
      out.write("\t\t<input type=\"submit\" id=\"home_signup\" name=\"action:signup\" value=\"SignUp\"/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("Copyright &copy CTLI 2014<br/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /home.jsp(49,2) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("message");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
